// C Header File Generated by XSI Shader Wizard

#ifndef aaOceanImgVecDisplace_H
#define aaOceanImgVecDisplace_H


////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miTag				texture;			// texture
	miVector			uv_coords;			// uv_coords
	miScalar			scale_height;
	miScalar			scale_chop;
	miScalar			fade;
} aaOceanImgVecDisplace_t;

#endif // aaOceanImgVecDisplace_H
