// aaOcean Image-based Vector Displace Shader
// Author: Amaan Akram 
// www.amaanakram.com
// aaOcean is free software and can be redistributed and modified under the terms of the 
// GNU General Public License (Version 3) as provided by the Free Software Foundation.
// GNU General Public License http://www.gnu.org/licenses/gpl.html

// C Header File Generated by XSI Shader Wizard

#ifndef aaOceanImgVecDisplace_H
#define aaOceanImgVecDisplace_H


////////////////////////////////////////////////////////////////
// Type definition

typedef struct
{
	miTag				texture;			// texture
	miVector			uv_coords;			// uv_coords
	miScalar			scale_height;
	miScalar			scale_chop;
	miScalar			fade;
} aaOceanImgVecDisplace_t;

#endif // aaOceanImgVecDisplace_H
